- name: Ensure Python 3 and pip3 are installed
  become: yes
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install python3.10-venv
  become: yes
  apt:
    name: python3.10-venv
    state: present

- name: Create directory for virtual environments
  become: no
  file:
    path: "{{ home_directory }}/.env"
    state: directory
    mode: 0755

- name: Create and activate virtual environment
  become: no
  command: python3 -m venv "{{ home_directory }}/.env/{{ env }}"
  args:
    creates: "{{ home_directory }}/.env/{{ env }}/bin/activate"
  register: venv_created

- name: Activate virtual environment and install packages
  become: no
  pip:
    name:
      - black
      - mypy
      - flake8
    virtualenv: "{{ home_directory }}/.env/{{ env }}"
    state: present
  when: venv_created is succeeded
